// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg8MAH84eoxKddAGzvRdQz7khQikxSWC0',
    appId: '1:905220878305:web:9f5643d21ad8287c70eca0',
    messagingSenderId: '905220878305',
    projectId: 'teman-bicara-hackfest',
    authDomain: 'teman-bicara-hackfest.firebaseapp.com',
    storageBucket: 'teman-bicara-hackfest.appspot.com',
    measurementId: 'G-8E81QLPTER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtOFoHP7kWNGV89d5W0PbJHHuALN43nfM',
    appId: '1:905220878305:android:20e907eaac379c8b70eca0',
    messagingSenderId: '905220878305',
    projectId: 'teman-bicara-hackfest',
    storageBucket: 'teman-bicara-hackfest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSSJ0c_K2qtOrg4ko7nvGgKRwB7pUUxNM',
    appId: '1:905220878305:ios:b852bc12d57a70df70eca0',
    messagingSenderId: '905220878305',
    projectId: 'teman-bicara-hackfest',
    storageBucket: 'teman-bicara-hackfest.appspot.com',
    iosBundleId: 'com.example.temanBicara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSSJ0c_K2qtOrg4ko7nvGgKRwB7pUUxNM',
    appId: '1:905220878305:ios:842c8afa3c6c9b4d70eca0',
    messagingSenderId: '905220878305',
    projectId: 'teman-bicara-hackfest',
    storageBucket: 'teman-bicara-hackfest.appspot.com',
    iosBundleId: 'com.example.temanBicara.RunnerTests',
  );
}
